#%RAML 0.8
---
title: Third&Loom
baseUri: https://thirdandloom.com/
version: v1

/swan:
  /account:
    get:
      description: Returns current logged user's information.
      responses:
          200:
            description: OK
            body:
              application/json:
                example: !include swan_account.txt

  /dress:
    /projects:
      /{projectId}:
        get:
          description: Returns the project with provided id.
          responses:
            200:
              description: OK
              body:
                application/json:
                  example: !include swan_dress_projects_id_get.txt
    /designs:
      /{designId}:
        /visuals:
          post:
            description: Creates a Visual for this design
            body:
              application/json:
                schema: |
                      {
                        "image": { 
                          "description": "Format base64", 
                          "required": true,
                          "type": "string"
                        },
                        "tags": { 
                          "description": "Labels added to this image",
                          "required": true,
                          "type": "array"
                        }
                      }
                example: |
                    {
                      "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYcAAAFzCAYAAADVHcVxAAAgAElEQVR4Xu292XMcWXbmeZmZzCTBFSAWYge4ANyTe1VlVVaVSlKPNGPTD+p+kamn50F/y/T/MtLDaMxUUlXpYTSm6jblxn3FTgAEQJAACXDNvc/vBg7SGQkyAMTmHvG52bXA4sv179zwz8++5ciRI98HbTWHwPfffx++++678O2334YtW7bE0dDQEPbs2RP27dsX2tvbQ0tLa+jo7Az797eF1ta2+P/t27eH9957L7z77rvhnXfeCZxHW/kQQC7IifHy5YuwuPg4LC09CePj42F6ajqMjY+F8bGx8ODBgygXhsuTT21CoFwIbBE5lAva6p6Xh80333zzGjm0tLSEnp6ecOjQIRuHQ09vbySKHTt2RFLwhw6EIFKovPyczPm8f/9+mJ+fD9evXQt//OMfw61bN8MHH3wQ3n///UjaDJFD5WVUT1cUOdSAtP1hzqc/4HnDfN8eJtu2bQvNRgB7GxtNQ9gf9re1hY6OztDc0hwaG5siMWzdujUONn/giBwqvzBc2+N......",
                      "tags": ["front", dress]
                    }
            responses:
              200:
                description: OK
                body:
                  application/json:
                    example: !include swan_dress_designs_visuals_post_response.txt
          

  /orders:
    get:
      description: Returns all the available configurations of Spree.
      responses:
         200:
           description: OK
           body:
             application/json:
               example: !include swan_spree_order_configs_get.txt

  /stories:
    post:
      description: Creates new text or image story for current logged user.
      body:
          application/json:
            schema: |
                  {
                    "story": {
                      "description": {
                          "required": true,
                          "type": "string"
                      },
                      "custom_story": {
                          "storyType": {
                            "description":"'text' or 'image'",
                            "required": true,
                            "type": "string"
                          },
                          "image": {
                            "description":"format base64",
                            "required": false,
                            "type": "string"
                          }
                      },
                      "required": true,
                      "type": "object"
                    },
                    "required": true,
                    "type": "object"
                  }
            example: |
                {
                  "story": {
                    "description": "test story"
                  },
                  "custom_story": {
                    "storyType": "image", 
                    "image": "data:image/jpg;base64,/9j/4UWO...qCWGL/AHL9OmZZV//Z"
                  }
                }

      responses:
          200:
            description: OK
            body:
              application/json:
                example: !include swan_stories_story_post.txt

          403:
            description: Forbidden |
              If story type is invalid (i.e. not “text” nor “image”)
            body:
              application/json:
                example: |
                  {  
                    'errors':'INVALID STORY TYPE' 
                  }

    get:
      description: |
        Retrieves necessary info to fill Story Page. It can be used for different purposes: 

        Retrieve main_period stories (expanded stories), n forward stories (collapsed) and m backward stories (collapsed). See Request Example 1. OR
        Retrieve only main_period stories (expanded). See Request Example 2. OR
        Retrieve only collapsed stories. See Request Example 3.

      queryParameters:
        requested_user_id:
          displayName: requested_user_id
          type: integer
          description: id of the owner of the story page
          example: 1
          required: true
        main_period:
          displayName: main_period
          type: string
          description: period  which will be shown as the main period of the Stories page (format can be 'yyyy/mm/dd' , 'yyyy/mm' or 'yyyy')
          example: '2001'
          required: true
        forward_periods:
          displayName: forward_periods
          type: integer
          description: amount of periods after the main_periods that frontend wants to show to User
          example: 2
          required: true
        backward_periods:
          displayName: backward_periods
          type: integer
          description: amount of periods before the main_periods that frontend wants to show to User.
          example: 1
          required: true
        retrieve_main:
          displayName: retrieve_main
          type: boolean
          description: true if main period must be retrieved, false if else
          example: true
          required: false
          default: true

      responses:      
        200:
          description: OK | Please notice the difference between the body of each story at the main period (expanded) and the body of each story at the side periods (collapsed) |
            Expanded story response parameters -- >
            
            id = story id;
            ownerId = id of the user who owns the story;
            ownerName = owner name;
            ownerAvatar.url = owner profile image url;
            createdDate = date at which story was created;
            description = story description;
            origin = “project” / “custom”;
            projectId = id of the project in case its origin is “project”;
            comments = array of comments;
            likes = amount of likes;
            type = “image” / “text” / “event” / “video”;
            image.url = url of original story image (this parameter only exists in case     type= “image”);
            image.expanded.url = url of expanded version of story image (this parameter only exists in case type= “image”);

            Collapsed story response parameters -- >

            id = story id;
            ownerId  = id of the user who owns the story;
            ownerAvatar.url = owner profile image url;
            createdDate = date at which story was created;
            description = story description;
            type= “image” / “text” / “event” / “video”;
            image.collapsed.url = url of collapsed version of story image (this parameter only exists in case type= “image”)

          body:
            application/json:
              example: !include swan_stories_story_get.txt

    /{storyId}:
      put:
        description: Updates story with provided id
        body:
          application/json:
            schema: |
                  {
                    "story": {
                      "description": {
                          "required": true,
                          "type": "string"
                      },
                      "custom_story": {
                          "storyType": {
                            "description":"'text' or 'image'",
                            "required": true,
                            "type": "string"
                          },
                          "image": {
                            "description":"format base64",
                            "required": false,
                            "type": "string"
                          }
                      },
                      "required": true,
                      "type": "object"
                    },
                    "required": true,
                    "type": "object"
                  }
            example: |
                {
                  "story": {
                    "description": "test story"
                  },
                  "custom_story": {
                    "storyType": "text"
                  }
                }
        responses:
          200:
            description: OK
            body:
              application/json:
                example: !include swan_stories_story_put.txt

          403:
            description: Forbidden |
              If story type is invalid (i.e. not “text” nor “image”) or if there is no story with provided id or if current logged user is not the owner of the story with provided id
            body:
              application/json:
                example: |
                  {  
                    'errors':'INVALID STORY TYPE' 
                  }
                  |
                  {  
                    'errors':'RECORD NOT FOUND' 
                  }
                  |
                  {  
                    'errors':'NOT OWNER' 
                  }

      delete:
        description: Deletes story with provided id
        responses:
            200:
              description: OK
            403:
              description: Forbidden |
                If current logged user is not the owner of the story with provided id
              body:
                application/json:
                  example: |
                    {
                      'errors':'NOT OWNER'
                    }
  /newsletter_subscriber:
    get:
      description: Returns all newsletter subscribers if current logged user is admin. It can be filtered by email(is not necessary to be admin)
      queryParameters:
        email:
          description: "Subscriber's email to filter by"
          example: "social@thirdandloom.com"
          type: string
          required: true 
      responses:
         200:
           description: OK
           body:
             application/json:
               example: !include swan_newsletter_subscribers_get.txt

    post:
      description: Creates a newsletter subscriber. If this email has been registered, the suscriber is retrieved
      body:
        application/json:
          schema: |
                {
                  "name": { 
                    "description": "subscriber's name", 
                    "required": false,
                    "type": "string"
                  },
                  "email": { 
                    "description": "subscriber'email. It has to be unique ",
                    "required": true,
                    "type": "string"
                  }
                }
          example: |
              { 
                "name": "swan",
                "email": "social@thirdandloom.com"
                
              }
      responses:
        200:
          description: OK
          body:
            application/json:
              example: |
                { "id": 1,
                  "name": "swan",
                  "email": "social@thirdandloom.com",
                  "activated": true
                }

    /{subscriberId}:
      delete:
        description: Desactivates the subscription for this subscriberId. The "activated" field is setted in false.
        responses:
          200:
            description: OK
          404:
            description: Not Found, user with provided id does not exist.
            body:
              application/json:
                example: '{"errors":"RECORD NOT FOUND"}'



/swan_user:
  /{userId}:
    get:
      description: Retrieves basic necessary user social info for lookbook.
      responses:
       200:
         description: OK
         body:
           application/json:
             example: !include swan_user_id_get.txt
    /social_info:
      get:
        description: Retrieves basic necessary user social info for lookbook.
        responses:
         200:
           description: OK
           body:
             application/json:
               example: !include swan_user_id_social_info_get.txt
    /projects:
      get:
        description: Retrieves basic necessary project info for every project (that is not a story) of user with provided id. It allows pagination. <br>
                     The project cards are returned showing the newest project first, and the oldest last.
        queryParameters:
          first:
            description: pagination offset. By default is 0
            type: integer
            required: false
            example: 1
          quantity:
            description: amount of projects to retrieve starting from specified offset. If is not specified, all projects are retrieved
            type: integer
            required: false
            example: 20
        responses:
          200:
           description: OK
           body:
             application/json:
               example: !include swan_user_id_projects_get.txt
          404:
            description: Not Found, user with provided id does not exist.
            body:
              application/json:
                example: '{"errors":"RECORD NOT FOUND"}'
    /stories:
      get:
        description: Retrieves basic necessary user social info for lookbook. It allows pagination.
        queryParameters:
          first:
            description: pagination offset. By default is 0
            type: integer
            required: false
            example: 1
          quantity:
            description: amount of stories to retrieve starting from the specified offset. If is not specified, all projects are retrieved
            type: integer
            required: false
            example: 20
        responses:
         200:
           description: OK
           body:
             application/json:
               example: !include swan_user_id_stories_get.txt


  /lost_password:
    post: 
        description: |
          Find a user by id and try to reset password with the new password. 
         
        body:
          application/json:
            schema: |
              {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                  "id": {
                    "description": "user id",
                    "type": "string",
                    "required": true

                  },
                  "resetPasswordToken": {
                    "description": "token sent with reset password email",
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  },
                  "passwordConfirmation": {
                    "type": "string",
                    "required": true
                  }

                }
              }
            example: |
              {
                "id": "1",
                "resetPasswordToken": "a token",
                "password": "12345678",
                "passwordConfirmation: "12345678"
              }

/lookbook:
  /user_info/{userId}:
    get:
      description: Retrieves basic necessary user info for lookbook.
      responses:
         200:
           description: OK
           body:
             application/json:
               example: !include lookbook_user_info_get.txt

  /social_info/{userId}:
    get:
      description: Retrieves basic necessary user social info for lookbook. 
      responses:
        200:
          description: OK
          body:
            application/json:
              example: !include lookbook_social_info_user_id_get.txt

  /projects/?user_id={user_id}&first={first}&limit={limit}:
    get:
      description: Retrieves basic necessary project info for every project (that is not a story) of user with provided id. It allows pagination. <br>
                   The project cards are returned showing the newest project first, and the oldest last.
      responses:
        200:
          description: OK
          body:
            application/json:
              example: !include lookbook_projects_get.txt
        404:
          description: Not Found, user with provided id does not exist.
          body:
            application/json:
              example: '{"errors":"RECORD NOT FOUND"}'


/api:
  /orders:
    post:
      description: Creates an empty Spree Order
      headers:
        X-Spree-Token:
          description: Spree Token to access Spree API. Returned in the response body of /swan/account endpoint. 
          type: string
          required: true
      responses:
          201:
            description: Created
            body:
              application/json:
                example: !include spree_api_order_post.txt

    /{orderNumber}:
      get:
        description: Gets desired Spree Order
        headers:
          X-Spree-Token:
            description: Spree Token to access Spree API. Returned in the response body of /swan/account endpoint. 
            type: string
            required: true
        responses:
            200:
              description: OK
              body:
                application/json:
                  example: !include spree_api_order_get.txt
      /line_items:
        post:
          description: Adds a line item to the Spree Order with the provided Spree Variant id and the quantity. |
                            The variant_id key must be retrieved from the response body of /swan/dress/projects/{project_id} endpoint. |
                            In case we want to charge a sketch, we will use sketchVariantId. And in case we want to charge the rest of the Design, we will use designVariantId.
          headers:
            X-Spree-Token:
              description: Spree Token to access Spree API. Returned in the response body of /swan/account endpoint. 
              type: string
              required: true
          body:
            application/json:
              schema: |
                {
                  "line_item": {
                      "variant_id": {
                          "required": true,
                          "type": "integer"
                      },
                      "quantity": {
                          "required": true,
                          "type": "integer"
                      }
                  },
                  "required": true,
                  "type": "object"
                }
          responses:
            201:
              description: Created
              body:
                application/json:
                  example: !include spree_api_add_line_item_to_order.txt

      /payments:
        get:
          description: See all the payments of the Spree Order. |
                        More information about payment status -> //guides.spreecommerce.com/developer/payments.html
          headers:
            X-Spree-Token:
              description: Spree Token to access Spree API. Returned in the response body of /swan/account endpoint. 
              type: string
              required: true
          responses:
            200:
              description: OK
              body:
                application/json:
                  example: !include spree_api_order_payment_get.txt

  /checkouts:
    /{orderNumber}:
      put:
        description: To transition an order to its next step |
                      {cart - address - delivery - payment - confirm - complete} |
                      More information about Spree Orders steps -> //guides.spreecommerce.com/developer/orders.html
        headers:
          X-Spree-Token:
            description: Spree Token to access Spree API. Returned in the response body of /swan/account endpoint. 
            type: string
            required: true
        responses:
          200:
            description: OK. |
              The following example represents the transition from 'cart' state to 'address' state. |
              The default addresses, those uploaded by the user previously, are assigned to the order.
            body:
              application/json:
                example: !include spree_api_checkout_cart_to_address.txt
